### ISSUE TITLE
Support for nested generics

### ISSUE THREAD

**Issue by anka-213** [Calcoph/hexpat-lsp#2]
If I write a patten like:
```
Foo<Bar<u8>> x@$;
Foo<Bar<Baz<u8,u16>>> y@$;
```
then imhex will happily accept it, but this tool treats it as a syntax error.

**Comment by Calcoph** [comment]
Fixed in commit [1cf9740](https://github.com/Calcoph/hexpat-lsp/commit/1cf9740027c944a19fa74aa79719dc67d982abd4)
